services:
  adminer-shopify:
    image: adminer:5.3.0
    container_name: adminer-shopify
    restart: unless-stopped
    networks:
      - shopify_network
    ports:
      - 8080:8080

networks:
  shopify_network:
    external: true
