services:
  adminer-shopify:
    image: adminer:5.3.0
    container_name: adminer-shopify
    restart: unless-stopped
    networks:
      - shopify_network
    ports:
      - 8080:8080
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '5'

networks:
  shopify_network:
    external: true
