services:
  logrotate:
    container_name: logrotate-shopify
    build:
      context: .
      dockerfile: Dockerfile
    image: logrotate:1.0
    restart: unless-stopped
    volumes:
      - ../../logs:/logs
    networks:
      - shopify_network
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '5'

networks:
  shopify_network:
    external: true
