apiVersion: 1

datasources:
  - name: Grafana Mimir
    type: prometheus
    uid: mimir-datasource
    access: proxy
    url: http://mimir:9009/prometheus
    isDefault: true
    version: 1
    editable: true
    jsonData:
      # httpMethod: POST
      # httpHeaders:
      #   - name: X-Scope-OrgID
      #     value: default-tenant
