services:
  fluent-bit:
    image: fluent/fluent-bit:4.0.7
    container_name: fluent-bit-shopify
    restart: unless-stopped
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./parsers.conf:/fluent-bit/etc/parsers.conf
      - ../../logs:/app_logs
    env_file:
      - ../../.env
    ports:
      - '24224:24224'
    command: /fluent-bit/bin/fluent-bit -c /fluent-bit/etc/fluent-bit.conf
    networks:
      - shopify_network
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '20'

networks:
  shopify_network:
    external: true
