services:
  prometheus:
    image: prom/prometheus:v3.5.0
    container_name: prometheus-shopify
    restart: unless-stopped
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
      - prometheus-data:/prometheus
    ports:
      - '9090:9090'
    command:
      - --config.file=/etc/prometheus/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.time=2h
    networks:
      - shopify_network
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9090/-/ready']
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '20'

networks:
  shopify_network:
    external: true

volumes:
  prometheus-data:
