global:
  scrape_interval: 15s
  evaluation_interval: 15s

remote_write:
  - url: http://mimir:9009/api/v1/push

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'mimir'
    static_configs:
      - targets: ['mimir:9009']

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
